// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWUfCTnlP6e25KWUIisLwPyGO8r1Y2JO8',
    appId: '1:197191456387:web:7c8748699b3bb0b15f6db6',
    messagingSenderId: '197191456387',
    projectId: 'debug-farm-project',
    authDomain: 'debug-farm-project.firebaseapp.com',
    storageBucket: 'debug-farm-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6VG1021AoKdUoJJIoLVHiTh2AlECrPuY',
    appId: '1:197191456387:android:6fff8927d3403a9a5f6db6',
    messagingSenderId: '197191456387',
    projectId: 'debug-farm-project',
    storageBucket: 'debug-farm-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjjjLlD1VCxnOSB8at5TE7-5vewFsz1bo',
    appId: '1:197191456387:ios:d8160d4028eea6f95f6db6',
    messagingSenderId: '197191456387',
    projectId: 'debug-farm-project',
    storageBucket: 'debug-farm-project.appspot.com',
    iosClientId: '197191456387-n3n124a6foegebgch4fqt27qduln74eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.debugApp6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjjjLlD1VCxnOSB8at5TE7-5vewFsz1bo',
    appId: '1:197191456387:ios:d8160d4028eea6f95f6db6',
    messagingSenderId: '197191456387',
    projectId: 'debug-farm-project',
    storageBucket: 'debug-farm-project.appspot.com',
    iosClientId: '197191456387-n3n124a6foegebgch4fqt27qduln74eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.debugApp6',
  );
}
